import { Kashrut } from "../components/interface-user/Kashrut";

export const En = {
    translation: {
        ManagerPhone: '050-950-5023',
        CompanyPhone: '054-290-2590',
        CompanyEmail: 'service@scoopcatering.com',
        sortBy: 'SortBy',
        first_name: 'First Name',
        last_name: 'Last Name',
        gender: 'Gender',
        status: 'Status',
        birthdate: 'Birthdate',
        email: 'Email',
        hebrew: 'hebrew',
        english: 'english',
        Login: 'Login',
        Register: 'Register',
        BookAnEvent: 'Book an event',
        gallery: 'gallery',
        ContactUs: 'Contact Us',
        shabatMenu: 'shabat menu',
        EventBooking: 'Event booking',
        ScoopCatering: 'Scoop Catering',
        OurStory: 'Our story',
        OurCustomers: 'Our customers',
        OurTeam: 'our team',
        Kashrut: 'Kashrut',
        ShoppingCart: 'Shopping cart',
        payment: 'payment',
        checkout: 'checkout',
        PreparedFoodCategories: 'Prepared food categories',
        ComeAndTasteTheShabbatFood: 'Come and taste the Shabbat food',
        ourTeamTitle1: '.At Scoop Catering service is always our top priority',
        ourTeamTitle2: `.We know how special and important your event is to you, which is why it is important to us as well`,
        ourTeamTitle3: `,Our staff at Scoop are always kind and smiling`,
        ourTeamTitle4: `.And will provide your guests with a personal service at a level that will not be forgotten for them`,
        ourTeamTitle5: `.Every event has an "event manager" who makes sure everything is perfect`,
        ourTeamTitle6: `.His job is also to be attentive to your special needs and requests from the beginning of the event to the end`,
        ourTeamTitle7: `.So you can relax and enjoy the event`,
        ourTeamLable2: `Our team at events`,
        ourStoryLable1: `Personal attitude and uncompromising quality are the secret of our success`,

        OurCustomersLable: `Our customers`,

        ourStoryLable2: `Catering owners`,
        ourStoryTitle1: `Started as a small cafe in Beit Shemesh, Gary Shikman and Aryeh Ben Hamo, both with experience`,
        ourStoryTitle2: `Rich in the field of food. Understood that there is a lack of catering places that provide personal service and quality food`,
        ourStoryTitle3: `The new place prospered, and within a year of opening, the partners had already opened the next branch in Efrat. currently`,
        ourStoryTitle4: `Provides the same vision for service and quality, both in the dairy kitchen and in the company's meat kitchen, which provide daily service`,
        ourStoryTitle5: `For companies, institutions, and events of all sizes and budgets`,
        ourStoryTitle6: `.In recent years, Michael Smigel has joined the company in expanding its activities to new audiences outside Gush Etzion and Beit Shemesh`,
        // cart
        emptyCart: `No items yet!`,
        ToTheShoppingCart: `Shopping Cart`,
        toCheckout: 'checkout',
        addProductsLable: `Add products to cart`,
        addToCart: `Add to cart`,
        product1: `Salomon in teriyaki sauce`
    }
}