import { Kashrut } from "../components/interface-user/Kashrut";

export const En = {
    translation: {
        //manger interface
        mangerInterface: 'manger interface',
        ManagerPhone: '050-950-5023',
        CompanyPhone: '054-290-2590',
        CompanyEmail: 'service@scoopcatering.com',
        sortBy: 'SortBy',
        first_name: 'First Name',
        last_name: 'Last Name',
        gender: 'Gender',
        status: 'Status',
        birthdate: 'Birthdate',
        email: 'Email',
        name: 'Name',
        EventType: 'Event type',
        NumberOfGuests: 'Number of guests',
        fleshy: 'Fleshy',
        milky: 'Milky',
        hebrew: 'hebrew',
        english: 'english',
        Login: 'Login',
        Register: 'Register',
        BookAnEvent: 'Book an event',
        gallery: 'gallery',
        soon: 'comming soon...',
        ContactUs: 'Contact Us',
        shabatMenu: 'shabbat menu',
        menuTitle: `Hi you have arrived at Scoop's ordering system
        Feel free to choose your favorite food`,
        EventBooking: 'Event booking',
        ScoopCatering: 'Scoop Catering',
        OurStory: 'Our story',
        OurCustomers: 'Our customers',
        OurTeam: 'our team',
        Kashrut: 'Kashrut',
        ShoppingCart: 'Shopping cart',
        payment: 'Payment',
        checkout: `Checkout`,
        homePageTitel: 'Service is our taste',
        MenusForEvents: 'Events',
        FoodReadyToShabat: 'Shabbat Food',
        Galleries: 'Galleries',
        homePageTitel2: 'A selection of Shabbat dishes from Scoop Catering',
        SearchResults: 'Search Results',
        searchPlaceholder: ' Enter product to search ...',
        searchMessage: 'Enter a product to search',
        NoResults: "No Results",
        PreparedFoodCategories: 'Prepared food categories',
        ComeAndTasteTheShabbatFood: 'Come and taste the Shabbat food',
        ourTeamTitle1: '.At Scoop Catering service is always our top priority',
        ourTeamTitle2: `.We know how special and important your event is to you, which is why it is important to us as well`,
        ourTeamTitle3: `,Our staff at Scoop are always kind and smiling`,
        ourTeamTitle4: `.And will provide your guests with a personal service at a level that will not be forgotten for them`,
        ourTeamTitle5: `.Every event has an "event manager" who makes sure everything is perfect`,
        ourTeamTitle6: `.His job is also to be attentive to your special needs and requests from the beginning of the event to the end`,
        ourTeamTitle7: `.So you can relax and enjoy the event`,
        ourTeamLable2: `Our team at events`,
        ourStoryLable1: `Personal attitude and uncompromising quality are the secret of our success`,

        OurCustomersLable: `Our customers`,

        ourStoryLable2: `Catering owners`,
        ourStoryTitle1: `Started as a small cafe in Beit Shemesh, Gary Shikman and Aryeh Ben Hamo, both with experience`,
        ourStoryTitle2: `Rich in the field of food. Understood that there is a lack of catering places that provide personal service and quality food`,
        ourStoryTitle3: `The new place prospered, and within a year of opening, the partners had already opened the next branch in Efrat. currently`,
        ourStoryTitle4: `Provides the same vision for service and quality, both in the dairy kitchen and in the company's meat kitchen, which provide daily service`,
        ourStoryTitle5: `For companies, institutions, and events of all sizes and budgets`,
        ourStoryTitle6: `.In recent years, Michael Smigel has joined the company in expanding its activities to new audiences outside Gush Etzion and Beit Shemesh`,
        // cart
        emptyCart: `No items yet!`,
        ToTheShoppingCart: `Shopping Cart`,
        ToTheShop: 'Back to menu',
        toCheckout: 'checkout',
        addProductsLable: `Add products to cart`,
        SelectAnOption: 'Select option',
        addToCart: `Add to cart`,
        product1: `Salomon in teriyaki sauce`,
        scoop: 'Scoop',
        OurAddress: 'Our Address',
        OpeningHours: 'Opening Hours',
        PersonalInformation: 'Personal Information',
        mailAdress: 'Email Adress',
        FirstName: 'First Name',
        LastName: 'Last Name',
        phone: 'Phone',
        anotherPhone: 'Another Phone',
        address: 'Address',
        OrderSummary: 'Order Summary',
        Items: 'Items',
        InterimTotal: 'Interim Total',
        ShippingCost: 'Shipping Cost',
        Total: 'Total',
        deliveryDetails: 'Delivery Details',
        AreaOrCity: 'Area / city',
        BeitShemesh: 'Beit Shemesh',
        GushEtzion: 'Gush Etzion',
        Jerusalem: 'Jerusalem',
        Modiin: `Modi'in`,
        Raanana: 'Raanana',
        shippingMethod: 'Please select shipping method',
        shippingMethod1: 'Pickup',
        shippingMethod2: 'Home delivery',
        shippingMethod3: 'Surprise Orders /Different address',
        InvoiceDetails: 'Invoice Details',
        Street: 'Street',
        buildingNumber: 'building',
        ApartmentNumber: 'Apartment',
        sameShippingAndAccountDetails: 'Shipping details and account details are the same',
        CouponCode: 'Coupon Code',
        EnterCouponCode: 'Enter coupon code',
        ActivateCoupon: 'Activate',
        ActivateCode: 'Activate',
        CommentsToOrder: 'Comments to order',
        ApprovalOfRegulations: 'Approval of regulations: Prepare regulations',
        SaveDetails: 'Save details for next time',
        ContinueToPay: 'To Payment',
        // payment page
        FormOfPayment: 'Form of payment',
        CardNumber: 'Card Number',
        Expiration: 'Expiry',
        CVV: 'CVV',
        Id: 'ID',
        AdditionalPayment: 'Additional payment options',
        AdditionalPayment_: `Bit / paybox / Bank transfer `,
        AdditionalPayment_1: `Contact the office at`,
        payBox: 'paybox',
        Bit: 'Bit',
        BankTransfer: 'Bank transfer',
        paymentMethod: 'Select Payment',
        TotalPayment: 'Total payment',
        MakePayment: 'Make payment',
        // shopping cart
        ProductName: 'Item Name',
        Amount: 'Amount',
        price: 'Price',
        //events page
        eventsTitel: 'Event booking',
        eventsLable: 'You have an event coming up soon?',
        eventsPiska: `Scoop Catering will be happy to be a culinary part of your important event,Fill in the details here and a Scoop representative will get back to you with a particularly affordable and delicious offer In the best tradition of Scoop, we are waiting for you!`,
        send: 'Send',
        Required: 'Required fill field',
        EventOption1: 'Wedding',
        EventOption2: 'Engagement',
        EventOption3: 'Brith',
        EventOption4: 'Bat Mitzvah',
        EventOption5: 'Bar Mitzvah',
        EventOption6: 'Sheva Brachos',
        EventOption7: 'Party',
        EventOption8: 'Company Event',
        EventOption9: 'Camp',

        //footer section
        lableInput: 'Join Updates from Scoop Catering',
        successEmail: 'The email was sent successfully',
        placeholderInput: 'Your email',
        ChainStores: 'Chain stores',
        Events: 'Events',
        PrivateEvents: 'Private events',
        Menus: 'Menus',
        WeddingMenu: 'Wedding menu',
        DairyMenu: 'Dairy menu',
        BasicDairyMenu: 'Basic dairy menu',
        Recommend: 'Recommend',
        orders: 'Orders',
        OrganizationsAndCompanies: 'Organizations and companies',
        OutdoorEvents: 'Outdoor events',
        InformationAndArticles: 'Information and articles',
        location: 'Mitzad',
        Copyright: 'all Copyright to Scoop Catering',
        Policy: 'Policy'

    }
}